---
- name: Install required packages
  apt:
    name:
      - nginx
      - php-fpm
      - certbot
      - python3-certbot-nginx
    state: present

- name: Ensure nginx is started and enabled
  service:
    name: nginx
    state: started
    enabled: yes

- name: Deploy custom nginx configuration
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_conf_path }}"
    owner: root
    group: root
    mode: '0644'
  vars:
    ssl_enabled: false
  notify: Reload Nginx

- name: Upload nginx config without SSL
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_conf_path }}"
  vars:
    ssl_enabled: false
  notify: Reload Nginx

- name: Ensure nginx is started
  service:
    name: nginx
    state: started
    enabled: yes

- name: Obtain SSL certificates with certbot
  command: >
    certbot --nginx -n --agree-tos --email {{ certbot_email }}
    -d {{ domain_name }}
  args:
    creates: "/etc/letsencrypt/live/{{ domain_name }}/fullchain.pem"
  notify: Reload Nginx

- name: Upload nginx config with SSL enabled
- template:
    src: nginx.conf.j2
    dest: "{{ nginx_conf_path }}"
  vars:
    ssl_enabled: true
  notify: Reload Nginx
