---
- name: Install required packages
  apt:
    name:
      - nginx
      - php-fpm
      - certbot
      - python3-certbot-nginx
    state: present

- name: Ensure nginx is started and enabled
  service:
    name: nginx
    state: started
    enabled: yes

- name: Deploy custom nginx configuration
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_conf_path }}"
    owner: root
    group: root
    mode: '0644'
  notify: Reload Nginx